# Be able to use the mouse
set -g mouse on

# Use vi key bindings
set-window-option -g mode-keys vi

# Vim-like nagivation of panes
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Use y as copy key in copy mode
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

#base16-shell enablement
set -g allow-passthrough 1

# ============================
# Plugins and their settings
# ============================
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Plugin specific configs
# tmux-resurrect
set -g @resurrect-capture-pane-contents 'on'

# tmux-contunuum
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
