setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# From agnoster oh-my-zsh theme
# zstyle ':completion:*' cache-path /Users/martinedviken/.oh-my-zsh/cache
# zstyle ':completion:*:*:*:*:processes' command 'ps -u martinedviken -o pid,user,comm -w -w'
# zstyle ':completion:*:*:*:users' ignored-patterns adm amanda apache at avahi avahi-autoipd beaglidx bin cacti canna clamav daemon dbus distcache dnsmasq dovecot fax ftp games gdm gkrellmd gopher hacluster haldaemon halt hsqldb ident junkbust kdm ldap lp mail mailman mailnull man messagebus mldonkey mysql nagios named netdump news nfsnobody nobody nscd ntp nut nx obsrun openvpn operator pcap polkitd postfix postgres privoxy pulse pvm quagga radvd rpc rpcuser rpm rtkit scard shutdown squid sshd statd svn sync tftp usbmux uucp vcsa wwwrun xfs '_*'
# zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
# zstyle ':completion:*' list-colors ''
# zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
# zstyle ':completion:*:*:*:*:*' menu select
# zstyle '*' single-ignored show
# zstyle ':completion:*' special-dirs true
# zstyle ':completion:*:cd:*' tag-order local-directories directory-stack path-directories
# zstyle -e :url-quote-magic url-globbers $'zmodload -i zsh/parameter;\n\t reply=( noglob\n\t\t ${(k)galiases[(R)(* |)(noglob|urlglobber|globurl) *]:-}\n\t\t ${(k)aliases[(R)(* |)(noglob|urlglobber|globurl) *]:-} )'
# zstyle :urlglobber url-local-schema ftp file
# zstyle ':url-quote-magic:*' url-metas '*?[]^(|)~#{}='
# zstyle :urlglobber url-other-schema http https ftp
# zstyle -e ':url-quote-magic:*' url-seps 'reply=(";&<>${histchars[1]}")'
# zstyle ':completion:*' use-cache yes

# source common configs from sh directory
if [ -f ~/.dotfiles/sh/aliases ]; then
    . ~/.dotfiles/sh/aliases
fi
if [ -f ~/.dotfiles/sh/colors ]; then
    . ~/.dotfiles/sh/colors
fi
if [ -f ~/.dotfiles/git/external/completion/git-prompt.sh ]; then    
    . ~/.dotfiles/git/external/completion/git-prompt.sh
fi
if [ -f ~/.dotfiles/sh/env_vars ]; then
    . ~/.dotfiles/sh/env_vars
fi
# Source zsh specific configs
if [ -f ~/.dotfiles/zsh/aliases ]; then
    . ~/.dotfiles/zsh/aliases
fi

# Prompt string configuration
setopt PROMPT_SUBST
NEWLINE=$'\n'
PS1=$'%{$BASE01%}%n@%m %{$BLUE%}%~ %{$YELLOW%}$(__git_ps1 "(%s)")%{$NC%} ${NEWLINE}%f$ '

# Source local config if it exists
if [ -f ~/.dotfiles/zsh/zshrc_local ]; then
    . ~/.dotfiles/zsh/zshrc_local
fi