setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# source common configs from sh directory
if [ -f ~/.dotfiles/sh/aliases ]; then
    . ~/.dotfiles/sh/aliases
fi
if [ -f ~/.dotfiles/sh/colors ]; then
    . ~/.dotfiles/sh/colors
fi
if [ -f ~/.dotfiles/git/external/completion/git-prompt.sh ]; then    
    . ~/.dotfiles/git/external/completion/git-prompt.sh
fi
if [ -f ~/.dotfiles/sh/env_vars ]; then
    . ~/.dotfiles/sh/env_vars
fi
# Source zsh specific configs
if [ -f ~/.dotfiles/zsh/aliases ]; then
    . ~/.dotfiles/zsh/aliases
fi

# Prompt string configuration
setopt PROMPT_SUBST
NEWLINE=$'\n'
PS1=$'%{$BASE01%}%n@%m %{$BLUE%}%~ %{$YELLOW%}$(__git_ps1 "(%s)")%{$NC%} ${NEWLINE}%f$ '

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        source "$BASE16_SHELL/profile_helper.sh"
        
base16_tomorrow-night-eighties

# Source local config if it exists
if [ -f ~/.dotfiles/zsh/zshrc_local ]; then
    . ~/.dotfiles/zsh/zshrc_local
fi
