setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# source common configs from sh directory
if [ -f ~/.dotfiles/sh/aliases ]; then
    . ~/.dotfiles/sh/aliases
fi
if [ -f ~/.dotfiles/sh/colors ]; then
    . ~/.dotfiles/sh/colors
fi
if [ -f ~/.dotfiles/git/external/completion/git-prompt.sh ]; then    
    . ~/.dotfiles/git/external/completion/git-prompt.sh
fi
if [ -f ~/.dotfiles/sh/env_vars ]; then
    . ~/.dotfiles/sh/env_vars
fi

autoload -Uz compinit && compinit

# Prompt string configuration
setopt PROMPT_SUBST
NEWLINE=$'\n'
PS1=$'%{$BASE01%}%n@%m %{$BLUE%}%~ %{$YELLOW%}$(__git_ps1 "(%s)")%{$NC%} ${NEWLINE}%f$ '

# Source local config if it exists
if [ -f ~/.dotfiles/zsh/zshrc_local ]; then
    . ~/.dotfiles/zsh/zshrc_local
fi